/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { GridItems, GridVariant } from "./components/c3-grid/c3-grid.types";
export namespace Components {
    interface C3Card {
        /**
          * The Card's display variant.
         */
        "variant": string;
    }
    interface C3Grid {
        /**
          * Evaluate if default slot exists for Smart Grid.
         */
        "hasDefaultSlot": boolean;
        /**
          * Evaluate if first slot has content.
         */
        "hasFirstSlot": boolean;
        /**
          * Evaluate if fourth slot has content.
         */
        "hasFourthSlot": boolean;
        /**
          * Evaluate if second slot has content.
         */
        "hasSecondSlot": boolean;
        /**
          * Evaluate if third slot has content.
         */
        "hasThirdSlot": boolean;
        /**
          * The Number of Items to display for Smart Grid in Slot One: 2|3|4
         */
        "items": GridItems;
        /**
          * The type of layout to display. Smart allows infinite items and the rest are slotted between one - four named slots.
         */
        "variant": GridVariant;
    }
}
declare global {
    interface HTMLC3CardElement extends Components.C3Card, HTMLStencilElement {
    }
    var HTMLC3CardElement: {
        prototype: HTMLC3CardElement;
        new (): HTMLC3CardElement;
    };
    interface HTMLC3GridElement extends Components.C3Grid, HTMLStencilElement {
    }
    var HTMLC3GridElement: {
        prototype: HTMLC3GridElement;
        new (): HTMLC3GridElement;
    };
    interface HTMLElementTagNameMap {
        "c3-card": HTMLC3CardElement;
        "c3-grid": HTMLC3GridElement;
    }
}
declare namespace LocalJSX {
    interface C3Card {
        /**
          * The Card's display variant.
         */
        "variant"?: string;
    }
    interface C3Grid {
        /**
          * Evaluate if default slot exists for Smart Grid.
         */
        "hasDefaultSlot"?: boolean;
        /**
          * Evaluate if first slot has content.
         */
        "hasFirstSlot"?: boolean;
        /**
          * Evaluate if fourth slot has content.
         */
        "hasFourthSlot"?: boolean;
        /**
          * Evaluate if second slot has content.
         */
        "hasSecondSlot"?: boolean;
        /**
          * Evaluate if third slot has content.
         */
        "hasThirdSlot"?: boolean;
        /**
          * The Number of Items to display for Smart Grid in Slot One: 2|3|4
         */
        "items"?: GridItems;
        /**
          * The type of layout to display. Smart allows infinite items and the rest are slotted between one - four named slots.
         */
        "variant"?: GridVariant;
    }
    interface IntrinsicElements {
        "c3-card": C3Card;
        "c3-grid": C3Grid;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "c3-card": LocalJSX.C3Card & JSXBase.HTMLAttributes<HTMLC3CardElement>;
            "c3-grid": LocalJSX.C3Grid & JSXBase.HTMLAttributes<HTMLC3GridElement>;
        }
    }
}
